"""
Definition de mots clés pour les descriptions de cuttings de forages.
:copyright: 2021  Y. N'DEPO & O. Kaufmann 
"""

# =========== LEXIQUE ===========
LEXICON = {'lithology': ['Monzonite', 'Combarbalite', 'Sable', 'Molasse ', 'Cargneule', 'Bauxite', 'Gneiss', 'éclogite', 'Gabbro', 'Cipolin', 'Marbre', 'Tuffeau', 'Gypse', 'Basalte', 'Grès', 'tillite', 'Jaspe', 'anhydrite', 'Houille', 'Sablo-graveleux', 'Arkose', 'Bentonite', 'Sablo-argileux', 'Glauconite', 'Quartzite', 'Ignimbrite', 'Molasse', 'Cendres', 'Phtanite', 'Micaschiste', 'Granite', 'Tuf volcanique', 'Craie', 'Sablo-limoneux', 'Sablo-caillouteux', 'Lignite', 'Péridotite', 'Calcaire', 'Lapillis', 'Schisto-charbonneux', 'Cinérites', 'Aplite', 'Sablo-graveleuse', 'Cendre', 'Porphyre', 'brèche', 'Leptynite', 'Rhyolite', 'Dolérite', 'Halite', 'Trachyte', 'Kimberlite', 'Alios', 'Diorite', 'Dolomie', 'Cinérite', 'Sablo-cendreux', 'Silex', 'Dacite', "Granite d'anatexie", 'Gravier', 'Phonolite', 'Pierre coquillière', 'Diatomite', 'Andésite', 'Pyroxénite', 'Argile', 'Carbonatite', 'Glauconie', 'Pegmatite', 'Conglomérat', 'Pierre coquillère', 'Anthracite', 'Obsidienne', 'Silcrète', 'Brèche', 'Marne', 'Kersantite', 'poudingue', 'Syénite', 'Ardoise', 'Tuf', 'Radiolarite', 'Ponce', 'Anatectite', 'Ophite', 'Sablo-limoneuse', 'Schiste', 'Poudingue', 'Amphibolite', 'Tourbe'], 'material': ['Brique', 'Béton', 'Scorie', 'Caillou', 'Laitier', 'Scories', 'Remblai', 'Briquaillon', 'Briques', 'Pierre'], 'modifier': ['Sablo-limoneuse', '-(\\w+eu(?:x|se|ses)?)', 'Limono-argileux', 'Sablo-caillouteux', 'Sablo-graveleux', 'Limono-sableux', 'argileux', 'Limono-sableuse', 'Gravelo-limoneuses', 'Schisto-charbonneux', 'Sablo-cendreux', 'Sablo-argileux', 'Sablo-graveleuse', 'Sablo-limoneux'], 'quantity': [], 'grainsize': [], 'colour': ['Bleu', 'Bleues', 'Jaunâtres', 'violet', 'Gros', 'Vert-de-gris', 'Jaune-vert', 'Beige/brun', 'Noires', 'Jaunâtre', 'Beige', 'Argent', 'Sableuses', 'Grise', 'Blanc-gris', 'lie-de-vin', 'Noir-brun', 'Rouge', 'Vers', 'Magenta', 'Brun-gris', 'Jaune-ocre', 'Sableuse', 'Noirs', 'Gris/noir', 'Noir', 'Bleuâtre', 'Lie-de-vin', 'Jaune/kaki', 'Gris/rouges', 'Hétérogènesgris', 'Noire', 'Jaunes', 'Orange', 'Grise-verdâtre', 'Noir/rouge', 'Grises', 'Jaune', 'Rouge-orange', 'Rougeâtre', 'Jaune-gris', 'Gris', 'Divers', 'Blanc', 'vert', 'Limono-sableuse', 'Rouges', 'Brun-jaune', 'Rose', 'Marron', 'mauve', 'Bleus', 'Turquoise'], 'synonyms': {}, 'splitters': [' avec ', ' de ', ' cont(?:ient|enant) ', '\\. '], 'parts_of_speech': {'noun': ['lithology'], 'adjective': ['colour', 'grainsize', 'modifier'], 'subordinate': ['quantity']}}

# =========== COULEURS ===========
COLORS = None